### ISSUE TITLE
Can't run Python extensions which require "tkinter" module

### ISSUE THREAD

**Issue by bastianilso** [flathub/org.inkscape.Inkscape#101]
Inkscape allows installation of python extensions, many of which rely on the tkinter toolkit. But when runnning an extension, the following error appears:

```
Traceback (most recent call last):
  File "/home/user/.var/app/org.inkscape.Inkscape/config/inkscape/extensions/removeDuplicateLines.py", line 29, in <module>
    from tkinter import messagebox
ModuleNotFoundError: No module named 'tkinter'
```

The Scribus flatpak app had a similar issue, which was solved, probably the solution for Inkscape is very similar:

https://github.com/flathub/net.scribus.Scribus/issues/34

**Comment by hfiguiere** [comment]
which extension?

**Comment by hfiguiere** [comment]
There will be a test build on https://github.com/flathub/org.inkscape.Inkscape/pull/102

feel free to test it.

**Comment by bastianilso** [comment]
@hfiguiere i was testing this one:

http://cutlings.wasbo.net/inkscape-extension-removeduplicatelines/

thanks for the test build. how do i try it?
