### ISSUE TITLE
You can not select icc profile.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.inkscape.Inkscape#11]
The icc profile can not be selected.
The predefined path is `/usr/share/color/icc` and flatpak can not access that directory.
The new path is `/run/host/usr/share/color/icc`

Actually, no application can see icc profiles.

**Comment by alexb3d** [comment]
Sorry, there is no new directory.  The same goes for Gimp, Krita, Darktable, etc. But Blender of Flatpak if you can access the ICC profiles.
[Blender](https://yadi.sk/i/4XxhosH_3W5giQ)

**Comment by hoxia** [comment]
This bug is still present in the Flatpak release of Inkscape 1.0.

**Comment by hfiguiere** [comment]
no work has been done toward this yet.

**Comment by alexb3d** [comment]
Possibly this is the error. user-share?
[https://drive.google.com/open?id=14rIGuCGSs1gkt0vOyKdyRJvStzUV1zP-
](url)
This is important, if you want to send a poster to the press or if you work in professional environments with the calibrated monitor.

Wonderful the new Inkscape! Congratulations!

**Comment by hfiguiere** [comment]
This should be fixed.

**Comment by alexb3d** [comment]
It works excellent. Thank you very much!
