### ISSUE TITLE
Merge Styles into CSS... extension fails, missing 'cssselect' module

### ISSUE THREAD

**Issue by skierpage** [flathub/org.inkscape.Inkscape#112]
I filed Inkscape [inbox issue 6901](https://gitlab.com/inkscape/inbox/-/issues/6901), then realized the flatpak manifest seems to be separate. In case the issue belongs here instead, here it is:

In the Inkscape flatpak (both stable and beta), choosing the command Extensions > Stylesheet > Merge Styles into CSS... fails. This is probably, like issue #2886, because the python cssselect module isn't included.

#### Steps to reproduce:

- open Inkscape
- create new document
- choose Extensions > Stylesheet > Merge Styles into CSS...
- enter a New Class Name, e.g. "test"
- click [Apply]

#### What happened?

A dialog appears
> Inkscape has received additional data... The script did not return an error...
>
> ...
>   File "/app/share/inkscape/extensions/inkex/css.py", line 27, in <module>
>     import cssselect
> ModuleNotFoundError: No module named 'cssselect'

#### What should have happened?
No error.

Presumably, the Flatpak manifest [here it is for flathub stable](https://github.com/flathub/org.inkscape.Inkscape/blob/master/org.inkscape.Inkscape.json) needs to include a python3-cssselect module.

Sample attachments:

#### Version info
```
Inkscape 1.2-beta (1b65182ce9, 2022-04-05)

    GLib version:     2.72.0
    GTK version:      3.24.33
    glibmm version:   2.66.1
    gtkmm version:    3.24.5
    libxml2 version:  2.9.12
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.50.6
    HarfBuzz version: 3.0.0

    OS version:       GNOME 42 (Flatpak runtime)

```

**Comment by nathanal** [comment]
Just to piggy-back on this issue, python3-packaging is also a new dependency (because distutils is set to be deprecated, https://gitlab.com/inkscape/extensions/-/merge_requests/368). This is used by our scour extension (by the script that calls/runs scour).

**Comment by hfiguiere** [comment]
I can't reproduce in stable (1.1)
