### ISSUE TITLE
Spelling checker. Unable to select the language

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.inkscape.Inkscape#12]
Spelling checker. Unable to select the language
It does not show any language.
aspell is installed, it does not take effect.

**Comment by rugk** [comment]
Same here. I guess, the flatpak just does not bundle all the langauges. And what is installed on the host does not matter.

Likely related to https://github.com/flathub/org.inkscape.Inkscape/issues/42

**Comment by alexb3d** [comment]
For some terrible reason Flatpak does not install languages ​​and other things.
You need to use the terminal... `$ flatpak update`
