### ISSUE TITLE
update Inkscape.org when flatpak version changes

### ISSUE THREAD

**Issue by skierpage** [flathub/org.inkscape.Inkscape#133]
I [complained](https://gitlab.com/inkscape/inkscape-web/-/issues/629#note_1173014652) that Inkscape's 1.2.1 release page https://inkscape.org/release/1.2.1/gnulinux/ doesn't mention the flatpak available here the way that the [0.92.4 Linux download page](https://inkscape.org/release/0.92.4/gnulinux/) does.

In response Martin Owens from the project said 
> If you know or would like to get in touch with the flatpak creators/maintainers for the inkscape flatpak, I'd be happy to invite them to keep the flatpak record up to date here. If it's something they wanted to do of course, because it is a bit more work for them.

The Inkscape web site seems to use Django CMS; I don't know what "flatpak record" you would update to make it show as a download.

**Comment by hfiguiere** [comment]
There is nothing we can do on this side. 1.2.2 was published.

**Comment by hfiguiere** [comment]
(give it a few hours for the flatpak to be updated, it's just being build as we speak)

**Comment by cho2** [comment]
@skierpage responded on gitlab
