### ISSUE TITLE
Replace x11 permission with x11-fallback

### ISSUE THREAD

**Issue by rugk** [flathub/org.inkscape.Inkscape#138]
The GNOME Software considers applications requiring x11 as unsafe. There's a way to declare it uses Wayland, but can use x11 as a fallback, on desktop environments where Wayland doesn't run.

It would be great if the flatpak could use `fallback-x11`  instead of `x11` permission.
I have temporarily tried changing this with Flatseal and it does start, at least, anyway. Or, of course, if it is 100% Wayland compatible, just remove the permission altogether.

More info here:
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/770#note_1136536

copied from https://github.com/flathub/org.gnome.Evolution/issues/49

**Comment by rugk** [comment]
Ah now saw https://github.com/flathub/org.inkscape.Inkscape/blob/8b5d351804aa5d6e7902d1ea4d3e82a83104bd1a/README.md#permissions-rationale and https://github.com/flathub/org.inkscape.Inkscape/issues/101 … hmm, too bad.

**Comment by hfiguiere** [comment]
It's documented.
