### ISSUE TITLE
The Inkscape on Flathub isn't latest version and old Gnome runtime

### ISSUE THREAD

**Issue by skierpage** [flathub/org.inkscape.Inkscape#14]
I wanted to use Inkscape, so I ran `flatpak install flathub org.inkscape.Inkscape` on my Fedora 28 (KDE spin) running Flatpak 0.11.8.3. `flatpak run org.inkscape.Inkscape --version` reports
: Inkscape 0.92.2 2405546, 2018-03-11
But the latest version according to https://inkscape.org/en/release/ is 0.92.**3**.

For what it's worth the Inkscape in the Fedora 28 distribution is this latest version, `/usr/bin/inkscape --version` reports
: Inkscape 0.92.3 (2405546, 2018-03-11)
it's suspicious that the number and date  are the same despite different versions.

Also, Flathub's Inkscape reported 
: Required runtime for org.inkscape.Inkscape/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.24)
and prompted me to download this runtime. But I already have org.gnome.Platform/x86_64/3.**28**. I would expect a recent build of Inkscape to use this latest stable Gnome platform.

Expected results:
Flathub should offer the latest Inkscape version built with latest Gnome.

(I originally mis-reported this as https://github.com/flatpak/flatpak/issues/1822)

**Comment by matze** [comment]
The version as specified in the manifest is in fact 0.92.3 however for some reason it was not built. I just bumped the platform version to 3.28 so let's see if this goes through.
