### ISSUE TITLE
Update GNOME runtime to 43

### ISSUE THREAD

**Issue by skierpage** [flathub/org.inkscape.Inkscape#140]
I guessed at the `org.inkscape.Inkscape.json` change in pull request #139 , but the build failed.

**Comment by 80501** [comment]
Update numpy  to 1.21.4 or newer,

**Comment by hfiguiere** [comment]
See #141

**Comment by hfiguiere** [comment]
without these it doesn't build. Not the right version.

**Comment by hfiguiere** [comment]
done
