### ISSUE TITLE
Feature request: flat app icon

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.inkscape.Inkscape#144]
The current app icon doesn't fit too well with GNOME's current design guidelines any more. It should be replaced with flat version of the icon: https://gitlab.com/inkscape/inkscape/-/blob/master/share/branding/inkscape-flat.svg

**Comment by hfiguiere** [comment]
It's up to upstream to decide. We don't change the icon upstream chose to use.

**Comment by doctormo** [comment]
I'm from upstream:

If Inkscape made a selection of icons from which a packagers could choose, would this help?

One advantage different icons give, is we can see which package a user is using just by their screenshots.

It's also unusual to have upstream dictate for example to Gnome and Kde both what icon they /must/ use, even if it would clash with their system's styling.

**Comment by julianfairfax** [comment]
@hfiguiere do you have a response to the above message? It would be nice to have a flat icon, and Inkscape already provides one. Upstream says the decision is on the Flatpak maintainers, so you can make this decision.

**Comment by hfiguiere** [comment]
No change. Flathub is NOT GNOME SPECIFIC (nor KDE). If upstream want this by default they should make it the default, and then it will magically happen. The icon named `org.inkscape.Inkscape` is the one being used. Nothing special is done about.

The policy for Flathub is to try to stay close to what upstream is shipping.

As for the comment from upstream, upstream (that same person) has already said they didn't care about the flatpak when they removed traces of it from the website.

**Comment by doctormo** [comment]
"That person" has a name and I'm calling you out as a liar, since I have never and would never say that I didn't care about the flatpak or would spend valuable time removing it from the website.

Here's a picture of the Inkscape website's release app today, with a flatpak entry:

![image](https://github.com/flathub/org.inkscape.Inkscape/assets/589384/1f2f25a6-9cc6-45d3-ac7e-99b8261b5279)

Here's the flatpak icon that I hand crafted for the releases app:

![image](https://github.com/flathub/org.inkscape.Inkscape/assets/589384/57f576bd-c5ec-4dd7-ba1e-dd0f0356bf45)

@julianfairfax Let me know which icon you want to use and I'll put it into the inkscape sources for you for the next release.

**Comment by hfiguiere** [comment]
>  or would spend valuable time removing it from the website

Cite:
https://github.com/flathub/org.inkscape.Inkscape/issues/87

**Comment by doctormo** [comment]
Sight: 
![image](https://github.com/flathub/org.inkscape.Inkscape/assets/589384/49b7912d-985c-4fc1-871b-fe29d70409c1)

How the hell did you get "removed traces", from ~nobody is maintaining it so nothing will change~

:potato:

**Comment by julianfairfax** [comment]
> @julianfairfax Let me know which icon you want to use and I'll put it into the inkscape sources for you for the next release.

I think [the flat icon](https://gitlab.com/inkscape/inkscape/-/blob/master/share/branding/inkscape-flat.svg) should be used for Inkscape. It is not GNOME-specific, but rather, all major operating systems and desktop environments use flat icons nowadays.

PS: Sorry for igniting this argument, it wasn't my intention.

**Comment by julianfairfax** [comment]
> I think [the flat icon](https://gitlab.com/inkscape/inkscape/-/blob/master/share/branding/inkscape-flat.svg) should be used for Inkscape. It is not GNOME-specific, but rather, all major operating systems and desktop environments use flat icons nowadays.

Although, the icon would be better with a shadow, like [this one](https://github.com/somepaulo/MoreWaita/blob/main/apps/scalable/org.inkscape.Inkscape.svg). That's better for GNOME, but also not specific. Apps like LibreOffice have shadows on their icons too, since no shadow doesn't look right on a desktop.
