### ISSUE TITLE
Cannot open .eps file

### ISSUE THREAD

**Issue by brittyazel** [flathub/org.inkscape.Inkscape#15]
When using the flathub version of Inkscape you cannot open a .eps file, even ones created within inkscape. Open/Import .eps files always results in a "failed to open..." error. The Inkscape version that is within the Archlinux repositories does not have this issue.

**Comment by matze** [comment]
Yes, looks like the last commit was a bit over ambitious and cleans the `bin` directory with the tools Inkscape uses for importing .eps files. I'll fix that later or tomorrow morning.

**Comment by matze** [comment]
Fixed and shipped.
