### ISSUE TITLE
Inkscape installed with Flathub not access Internet.

### ISSUE THREAD

**Issue by pedropaulomg** [flathub/org.inkscape.Inkscape#16]
When I execute the menu: File / Import Clipart and press the "search" button, Inkscape return this message: Could not connect to the Open Clipart Libary

![screenshot from 2018-07-24 19 37 13](https://user-images.githubusercontent.com/22965630/43198421-f742d76c-8fe4-11e8-84fa-91959feca77e.png)

**Comment by matze** [comment]
Hmm, even when running via `flatpak run --share=network org.inkscape.Inkscape` the problem persists …

**Comment by fbruetting** [comment]
Other programs (Gnome-Maps, Polari and FeedReader) seem to have that issue too, while others (Spotify, Firefox-DexEd, Minitube) work.

I had this with Geary: https://gitlab.gnome.org/GNOME/geary/issues/73#note_292069

**Comment by Alexander-Wilms** [comment]
This appears to be an upstream bug: https://bugs.launchpad.net/inkscape/+bug/1793108

**Comment by hfiguiere** [comment]
Upstream bug has been closed after saying things started working again. Can you check? And if it works, can you close this issue?

**Comment by hfiguiere** [comment]
I don't even see Import Clip Art on Inkscape 1.0

**Comment by eszlari** [comment]
https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#OpenClipart_Import_Removed

> The dialog and settings for importing images from OpenClipart have been removed due to the openclipart.org API being non-functional since mid-April 2019 with no information about a return date.

**Comment by hfiguiere** [comment]
So it can be closed.
