### ISSUE TITLE
Inkscape 1.4 - tinycss2 required for extensions and export

### ISSUE THREAD

**Issue by pricklygorse** [flathub/org.inkscape.Inkscape#186]
Running any extensions in Inkscape 1.4 fail due to the Python error `ModuleNotFoundError: No module named 'tinycss2'`

Right at the bottom of the full 1.4 release notes is a small note under Packaging mentioning this new requirement

"tinycss2 is now needed for Inkscape extensions (and export) to work ([Bug #5070](https://gitlab.com/inkscape/inkscape/-/issues/5070))."

Thanks

**Comment by doctormo** [comment]
The extensions dependancies are listed in this documentation https://inkscape.gitlab.io/extensions/python-dependencies.txt 

Every packager for every platform so far as ignored the extension team's dependency list; where would you expect to find these deps in the workflow for updating this flatpak?

**Comment by hfiguiere** [comment]
tbf I was expecting the package maintainer, ie you, to check these.

**Comment by doctormo** [comment]
Oh I'm not the package maintainer, I've been trying to get the keys to the actual people for a while. There doesn't seem to be a process, which is a shame.

Good of you to get the 1.4 out then.

**Comment by hfiguiere** [comment]
It's documented https://docs.flathub.org/docs/for-app-authors/maintenance#maintainer-access-to-flathub-application-repository
