### ISSUE TITLE
Canvas is lagging like crazy without device=dri enabled

### ISSUE THREAD

**Issue by archerallstars** [flathub/org.inkscape.Inkscape#189]
`device=dri` or GPU acceleration should be enabled by default. Without enabling this, Inkscape's canvas is lagging a lot on my system.

My GPU is Intel UHD Graphics 620 (KBL GT2).

**Without GPU acceleration:**

https://github.com/user-attachments/assets/946042d1-c7e1-45ef-b5bf-2df96ce3267f

**With GPU acceleration:**

https://github.com/user-attachments/assets/2d7fc27e-f38c-4ed8-8178-e782cbf01237

**Comment by hfiguiere** [comment]
![image](https://github.com/user-attachments/assets/1d74d220-ad3d-445b-883d-2aa969f58400)

**Comment by hfiguiere** [comment]
not sure how it was not in.

**Comment by archerallstars** [comment]
@hfiguiere 

I have re-uploaded 2 screen recordings in OP using H264 codec (previously H265).
