### ISSUE TITLE
Using as base app

### ISSUE THREAD

**Issue by singpolyma** [flathub/org.inkscape.Inkscape#27]
I want to use this as the base app for my app's flatpak build, since I need `inkscape` for my build and don't want to build it from source every time as part of mine.  When I add it to my manifest, it seems to unpack correctly, but my actual build says:

    inkscape: /lib/libm.so.6: version `GLIBC_2.27' not found (required by inkscape)

running `flatpak run org.inkscape.Inkscape` works fine... so not sure where this library conflict is coming from running `flatpak-builder`?  Any clues would be greatly appreciated :)

**Comment by TingPing** [comment]
In order to use a baseapp you must at all times use the exact same runtime as the base. That means `org.gnome.Platform//3.30` at the moment, you likely used something else.

**Comment by hfiguiere** [comment]
Lack of feedback. Closing.
