### ISSUE TITLE
Add UniConvertor

### ISSUE THREAD

**Issue by jurf** [flathub/org.inkscape.Inkscape#3]
Without it Inkscape cannot open `.cdr` files.

This is the message I get when I try to open one:

```
You need to install the UniConvertor software.
For GNU/Linux: install the package python-uniconvertor.
For Windows: download it from
https://sk1project.net/modules.php?name=Products&product=uniconvertor&op=download
and install into your Inkscape's Python location
```

**Comment by matze** [comment]
I will take care of that next week around Thursday or Friday. Thanks for the report!

**Comment by jurf** [comment]
Thanks!

**Comment by Jeansen** [comment]
I'd like to open an .ai file but unfortunately on Debian packages python-imaging and python-uniconvertor are no longer available and I do not want to clutter my system with old packages. So I thought the flatpak version would fit. But as far as I can tell uniconvertor is still not integrated :cry:

**Comment by jurf** [comment]
This should be a super-quick fix actually, if you wanna try it should be doable in like 15–20 minutes.

**Comment by Jeansen** [comment]
By all means, then please do it :smile:

**Comment by jurf** [comment]
Sorry, just using an old trick for getting new contributors. :wink:

I can’t do it ATM, but I’ll try later today (maybe). Though if you wanna try, feel free.

**Comment by Jeansen** [comment]
No problem :smile: I would gladly do it, but I am involved in other projects ATM and have no clue about the internals of flatpak.

**Comment by eszlari** [comment]
http://wiki.inkscape.org/wiki/index.php/Release_notes/1.0

> Extensions that previously used the UniConvertor library for saving/opening various file formats have been removed:

**Comment by jurf** [comment]
So what now?

**Comment by Jeansen** [comment]
Well, I think then it is obsolete now (or only applicable for older versions). I'll close it.

**Comment by hfiguiere** [comment]
To open .cdr file you need libcdr. This dependency is missing in the stable flatpak, I have a patch for issue #38 part of pr #40 

The beta flatpak for the 1.0 beta version  however has support for it.
