### ISSUE TITLE
Crash on newlines (and other text related input)

### ISSUE THREAD

**Issue by Moini** [flathub/org.inkscape.Inkscape#30]
Hi @matze ,

we've had a bug report about the flatpak version of Inkscape crashing on newlines, very similar to what is happening on Fedora - there, it seems to be an issue with the libraries / settings used for compiling (sorry, I don't know much more than that... :-( ).

The corresponding bug in our tracker is at 

https://gitlab.com/inkscape/inbox/issues/24

Would you be able to have a look at that?

**Comment by Moini** [comment]
Thanks for investigating more! Would it be possible to make a test flatpak, so we can direct the user to it to try out if it works/doesn't work?

I'll also ping @bryceharrington and @mclegrand - maybe they can give more info.

**Comment by matze** [comment]
> Would it be possible to make a test flatpak, so we can direct the user to it to try out if it works/doesn't work?

Yep: `flatpak install --user http://repo-test.flathub.org:8080/build-repo/1789/org.inkscape.Inkscape.flatpakref`. Seems to fix the issue indeed.

**Comment by Moini** [comment]
Thank you, @matze - I've linked the post for the affected users, so they can try it out, too.

**Comment by matze** [comment]
@TingPing how long are builds for a PR kept around?

**Comment by rszibele** [comment]
The PR solved the issue for me on Kubuntu 18.10, it no longer produces a crash when creating and editing/selecting text.

Tested manually by building and installing the branch locally:

    flatpak install flathub org.gnome.Sdk//3.30
    git clone --recursive https://github.com/flathub/org.inkscape.Inkscape
    cd org.inkscape.Inkscape/
    git checkout fix-30-crash-on-newlines
    flatpak-builder --repo=test build-directory org.inkscape.Inkscape.json
    flatpak --user remote-add --no-gpg-verify test test
    flatpak --user install test org.inkscape.Inkscape
    flatpak-run org.inkscape.Inkscape

After testing around for a while I got a different crash, but the error message seems vaguely related as it's also about the stl and it also happens in the one currently available on Flathub, not only this PR version:
* open inkscape
* create rectangle
* select "Fill bounded areas" tool
* click on the rectangle

```
richard@linux-desktop:~$ flatpak run org.inkscape.Inkscape

(process:2): Gtk-WARNING **: 11:07:39.790: Locale not supported by C library.
        Using the fallback 'C' locale.
/usr/include/c++/8.2.0/bits/stl_deque.h:1463: std::deque<_Tp, _Alloc>::reference std::deque<_Tp, _Alloc>::front() [with _Tp = Geom::Point; _Alloc = std::allocator<Geom::Point>; std::deque<_Tp, _Alloc>::reference = Geom::Point&]: Assertion '__builtin_expect(!this->empty(), true)' failed.

Emergency save activated!

Emergency save document locations:
  /home/richard/New document 1.2019_02_08_11_07_44.0.svg
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at www.inkscape.org
with a detailed description of the steps leading to the crash, so we can fix it.
```

**Comment by matze** [comment]
Jeez, I am honestly surprised by the lack of quality and lack of action shown by the Inkscape developers. The original issue is known for a year and only three weeks ago have they merged these fixes. Now there is this problem. @Moini could you encourage the devs to enable the same flags for development Fedora is using? All these potential out-of-bounds accesses seem ticking time bombs to me and closing the eye for a year is not helping anyone.

**Comment by Moini** [comment]
@matze Sorry, I don't know enough about this :-( 

I could make a bug report and point them to it, but I wouldn't understand what I'm writing about.

I'm only familiar with a bit of scripting and some general principles... If you create a report that contains the relevant info, I could still do the pointing. 

Do I understand correctly that aside from the crashes, this also has security implications? Maybe that would serve to get people's attention more.

**Comment by matze** [comment]
> Do I understand correctly that aside from the crashes, this also has security implications?

i had the same question but I am not knowledgable in that area to answer that. But I would at least sleep better if I knew that out-of-bounds access would crash rather than go unnoticed and affect the state of the program arbitrarily.

There was no older issue which tracked the problem when it first surfaced on Fedora?

**Comment by Moini** [comment]
I don't know, honestly. It got evident through Fedora because it appeared as a cluster of bug reports.

As we're currently migrating bugs from lp to gitlab, it's probably okay to make a new one for this on gitlab, and link to the one on lp. This offers a chance of just collecting the relevant info devs need for fixing the problem, to make it quick + easy.

**Comment by matze** [comment]
I will merge my PR so people using the Flathub version won't be affected by the original reported bugs. When I find the time I will open an issue on the Inkscape tracker.
