### ISSUE TITLE
Add beta branch

### ISSUE THREAD

**Issue by eszlari** [flathub/org.inkscape.Inkscape#33]
https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

1.0 pre release:
https://gitlab.com/inkscape/inkscape/tags/INKSCAPE_1_0_ALPHA
https://inkscape.org/gallery/item/13331/inkscape-1.0alpha.tar.bz2

**Comment by garrett** [comment]
Inkscape 1.0 beta 1 is now out:
https://inkscape.org/news/2019/09/08/inkscape-10-beta1-available-testing/

It'd be lovely to have this on Flathub. The AppImage they provide doesn't integrate properly with the system and python isn't supported (so most extensions silently fail).

As the Flathub version of Inkscape is amazing (it's what I use every day, thanks!), having the beta easily available as a Flatpak would be awesome!

**Comment by matze** [comment]
Fair enough, but I still have to catch up how to provide stable and beta channels. PRs are welcome of course.

**Comment by hfiguiere** [comment]
I think the beta branch in the repo needs to be created otherwise no one can submit a pull request.

**Comment by matze** [comment]
Okay, the title was very literal. [Here](https://github.com/flathub/org.inkscape.Inkscape/tree/beta) you go.

**Comment by hfiguiere** [comment]
I think it is #34 that should have been closed. For this one there is actually PR #39
