### ISSUE TITLE
Commit access

### ISSUE THREAD

**Issue by eszlari** [flathub/org.inkscape.Inkscape#34]
I would like to have commit access to help maintain this app and fix https://github.com/flathub/org.inkscape.Inkscape/issues/33 .

**Comment by matze** [comment]
Stupid question: why not just opening a pull request?

**Comment by eszlari** [comment]
You can't open PR for a new branch (beta)?

**Comment by hfiguiere** [comment]
and you can't change the base branch afterwards.

**Comment by hfiguiere** [comment]
There is a beta branch and PR #39 for the first beta build. I think that can be closed as it is unecessary.

(I do not have commit rights but PR against beta are possible now)
