### ISSUE TITLE
Inkscape is using fallback GTK theme

### ISSUE THREAD

**Issue by tannisroot** [flathub/org.inkscape.Inkscape#36]
Hi, I have Arch Linux and use Gnome 3.32. I've just installed Inkscape from Flathub and for some reason, its version of Inkscape looks pretty ugly:
![image](https://user-images.githubusercontent.com/10602045/54879478-6a54ce80-4e4a-11e9-809c-5227ef09de15.png)
I've tried running it from command line and I only see this single error:
```
Gtk-Message: 15:33:30.880: Failed to load module "canberra-gtk-module"
```
Is this an issue with the package itself or do I just have something missing on my system?

**Comment by TingPing** [comment]
It should be using Adwaita unless Inkscape is forcing a different name somewhere.

**Comment by DougBeney** [comment]
Happening on Ubuntu 19.10 as well.

**Comment by hfiguiere** [comment]
Does the 1.0 beta from flathub beta work better?

**Comment by DougBeney** [comment]
Yes! Works perfectly thanks. [How to get Inkscape Beta on Flatpak](https://inkscape.org/release/inkscape-1.0beta2/gnulinux/flatpak/dl/) for anyone else that didn't know how to install betas.

**Comment by hfiguiere** [comment]
Yes it does. It's a major change for 1.0. 

I just wanted to make sure it worked there.
