### ISSUE TITLE
error while trying to open Coreldraw files (.cdr) ... missing package dependency

### ISSUE THREAD

**Issue by aiamuzz** [flathub/org.inkscape.Inkscape#38]
`Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.`

```
For GNU/Linux: install the package python-uniconvertor.
For Windows: download it from
https://sk1project.net/modules.php?name=Products&product=uniconvertor&op=download
and install into your Inkscape's Python location
```

do we have to install `python-uniconvertor` on linux or should it be installed via a flatpak package ?

**Comment by aiamuzz** [comment]
ok i tried installing the package `python-uniconvertor` from here ... https://sk1project.net/modules.php?name=Products&product=uniconvertor&op=download

but Inkscape flatpak app is still throwing up the error ...

does it mean you'll have to create a flatpak package for this `python-uniconvertor` package ???

**Comment by hfiguiere** [comment]
Installing package on your system won't help because the flatpak is stand alone.

The flatpak is built without CDR support. If you want you can try the beta flatpak for 1.0beta 1.

Until the current release is updated (working on it).

**Comment by aiamuzz** [comment]
> If you want you can try the beta flatpak for 1.0beta 1.

where can i find or how can i install the beta flatpak versions of inkscape ?

**Comment by matze** [comment]
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.inkscape.Inkscape
```

**Comment by hfiguiere** [comment]
I have to admit I tried to find where this is documented / listed on flathub and couldn't.

**Comment by aiamuzz** [comment]
> ```
> flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
> flatpak install flathub-beta org.inkscape.Inkscape
> ```

worked for me the Beta version works with cdr files ... thanks @matze ...

**Comment by matze** [comment]
It should now also work with stable, if there are ongoing issues, just reopen this.
