### ISSUE TITLE
Crash on Division

### ISSUE THREAD

**Issue by nathanal** [flathub/org.inkscape.Inkscape#43]
### Steps to reproduce
1. Create two rectangles
2. Path > division on the two rectangles

See https://gitlab.com/inkscape/inbox/issues/397 and 094d2341faec7dbbb9336bd3f84ec20e5ecfd685 in 0.92.x branch

---

Here's a list of other crashes affected by the same type of error as https://github.com/flathub/org.inkscape.Inkscape/issues/30 . Would you like separate issues for each bug? 

Crash on Put on Path with Objects dialog open https://gitlab.com/inkscape/inbox/issues/421 see f5a3865836b69eaf3500e0ea1d256e8a15eaa5a6 in 0.92.x branch

Crash on select all with text on path https://gitlab.com/inkscape/inbox/issues/420 see 1a07842b3b8870ba06238a2a09ce97e0a07761e2 in 0.92.x branch

Crash with paintbucket tool https://gitlab.com/inkscape/inbox/issues/398 see see cbeb0db7ede1364170994e390829f48537d12268 in 0.92.x branch

All tested in 351ad9649e37 on Linux Mint 19.1 (sorry if this isn't the latest version, I'm having some problems updating flatpak programs atm)

**Comment by matze** [comment]
I guess we will have to wait for Inkscape to make a new 0.92.5 release …

**Comment by nathanal** [comment]
Alright, I'll close the issue then. 

Thanks for responding, I guess its not going to be a long wait anyway.

**Comment by matze** [comment]
> Thanks for responding, I guess its not going to be a long wait anyway.

I hope so, that looks pretty critical to me.
