### ISSUE TITLE
Aviso: Problema ao procurar por refs relacionadas: Erro ao resolver “sdk.gnome.org”: Nome ou serviço desconhecido

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.inkscape.Inkscape#5]
Instalando: org.inkscape.Inkscape/x86_64/stable
Aviso: Problema ao procurar por refs relacionadas: Erro ao resolver “sdk.gnome.org”: Nome ou serviço desconhecido
Instalando: org.inkscape.Inkscape/x86_64/stable de flathub
[####################] 3 delta parts, 21 loose fetched; 31219 KiB transferred in
Note that '/sysroot/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /sysroot/home/leandro/.local/share
- /usr/local/share/
- /usr/share/

Instalando: org.inkscape.Inkscape.Locale/x86_64/stable de flathub
[####################] 11 metadata, 3 content objects fetched; 403 KiB transferr

**Comment by bochecha** [comment]
This looks more like a general flatpak issue, rather than a bug in the Inkscape build.
