### ISSUE TITLE
Access remote network mounts

### ISSUE THREAD

**Issue by garrett** [flathub/org.inkscape.Inkscape#66]
Inkscape doesn't see GVFS or GIO mounts, such as remote servers. Usually, these show up in the sidebar of file selectors (open and save) and in Nautilus.

I've seen other apps have used the following:

```
--filesystem=xdg-run/gvfs
--talk-name=org.gtk.vfs
--talk-name=org.gtk.vfs.*
```

(Most mention just the filesystem one; not sure if the talk ones are needed.)

I've tried those as overrides and it still doesn't seem to work here. Perhaps Inkscape needs to be compiled with support? Or perhaps it's not gvfs support, but gio that's needed.

Alternatively, the file dialog portal is supposed to handle this. But that might not be an option for Inkscape?

**Comment by garrett** [comment]
Here's an example of Nautilus:

![Screenshot from 2020-09-24 17-32-26](https://user-images.githubusercontent.com/10246/94166756-01f60b80-fe8c-11ea-9b91-80f2161325c7.png)

It's in the sidebar with the eject buttons.

**Comment by garrett** [comment]
Aha! Going to flatseal and toggling on "D-Bus session bus" gets it working.

I wonder if it can be restricted without turning on that flag, and if (anything that makes it work) could be enabled by default.

**Comment by hfiguiere** [comment]
Just adding these do work.

**Comment by garrett** [comment]
@hfiguiere: @tigert and I used Flatseal to override those values, and it makes browsing work in the file selector. However, when you actually attempt open a file, it doesn't work... At least on sftp and Google Drive mounts. Not sure about other types of networked filesharing... but those probably also have the same problem (where it cannot actually open or save the file).

**Comment by hfiguiere** [comment]
There is a test build on #67 . I tried with that and could open a file from my sftp mount. Not touch permissions with Flatseal.

**Comment by garrett** [comment]
@hfiguiere: I just tested it and it works here! Thanks!!!

**Comment by hfiguiere** [comment]
I think there must be a difference between having the permission in the manifest and overriding on the command line, hence the need to use Flatseal.

Glad it's solved. The new build should appear in the next few hours.
