### ISSUE TITLE
Inkscape flatpak is still 0.9.2 

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.inkscape.Inkscape#7]
Hi, the inkscape 0.9.3 arrived, but the inkscape flatpak still 0.9.2 in my linuxmint 18.3 cinnamon 64 bit. I upgraded it but inkscape versión continue being 0.9.2. I know there is a complete pull request for.0.9.3 but  the versión in my computar is 0.9.2

**Comment by TingPing** [comment]
I already has 0.9.3.

**Comment by Lvaskz** [comment]
Hi, I know this is closed, but inkscape continue being 0.92.2 see:
![captura de pantalla de 2018-09-26 17-06-53](https://user-images.githubusercontent.com/29207169/46293318-6194d700-c550-11e8-826a-fdd8024cdeb6.png)

**Comment by matze** [comment]
Did you install it  by downloading a bundle directly from the Inkscape homepage? If so, please remove that and install through the instructions given on the flathub website.

**Comment by Lvaskz** [comment]
No, I installed from flathub.

**Comment by matze** [comment]
Okay you are right that the displayed version is 0.92.2 however this is an upstream issue. I suppose someone forgot to update the version number in the `configure.ac` file. If that really bothers you, please open an issue in the Inkscape bug tracker.

**Comment by Lvaskz** [comment]
ok
