### ISSUE TITLE
License for manifest?

### ISSUE THREAD

**Issue by rpavlik** [flathub/org.inkscape.Inkscape#77]
I'd like to build a gtkmm-based application as a flatpak, and I'd like to re-use this work, but I don't see a license notice on it. What license is this repo available under?

**Comment by hfiguiere** [comment]
tbf I assume it's all CC-0. We do a lot of copy paste between manifest. Nobody seem to have questionned this.

**Comment by rpavlik** [comment]
Ok, that matches with the default for the app stream metadata too, so that makes sense.
