### ISSUE TITLE
Removal from the Inkscape Website

### ISSUE THREAD

**Issue by doctormo** [flathub/org.inkscape.Inkscape#87]
The inkscape project is considering removing the flatpak format from the website's resources/downloads pages because of lack of maintenance. There is no maintainer of the flatpak/flathub format at this time and it means the project does not know when or if the format has been updated with any particular version.

If the flathub project would like to be linked correctly when updated, we would need someone who can be responsible just to make sure the resource object is up to date. It's not a lot of work, but it does need someone who knows what's going on in flathub world.

**Comment by hfiguiere** [comment]
You can file issues around here instead of claiming it's unmaintained. I make sure it is up to date, and there have been a few other contributors that help as well. We are just a bunch of volunteers mostly. Much like Inkscape

**Comment by doctormo** [comment]
No, I think you misunderstand. I don't claim the flathub/flatpak is unmaintained (or that inkscape is).

Only that *inside the inkscape project* the flatpak has no maintainer, there is no one who would report project known issues here, or tell the project that anything has happened. So the website can't maintain adding entries to a packaging format we have no information about.

This is a website only issue. If the view of this project is that the website link isn't needed, I can make sure others know to close reported issues about missing links to flatpak as intentional.

**Comment by hfiguiere** [comment]
This is not how I understood it.

> The inkscape project is considering removing the flatpak format from the website's resources/downloads pages because of lack of maintenance. There is no maintainer of the flatpak/flathub format at this time and it means the project does not know when or if the format has been updated with any particular version.

I went to Inkscape.org, click "download current version", landed here:
https://inkscape.org/release/inkscape-1.1/
Clicked Linux, clicked flatpak, landed here:
https://inkscape.org/release/inkscape-1.1/gnulinux/flatpak/dl/
These are the instruction to download from Flathub, the flathub build is managed here with this repo. It's maintained. 

> If the flathub project would like to be linked correctly when updated, we would need someone who can be responsible just to make sure the resource object is up to date. It's not a lot of work, but it does need someone who knows what's going on in flathub world.

You could link here https://flathub.org/apps/details/org.inkscape.Inkscape and this would provide the exact same thing.

So I still don't understand what I didn't get.

The things that sometime don't get updated is the release in the appstream/appdata file which requires us to patch and submit upstream... (it's not Flatpak specific but we rely on it)

**Comment by doctormo** [comment]
> https://inkscape.org/release/inkscape-1.1/gnulinux/flatpak/dl/

Who should make that entry? They don't get automatically created.

**Comment by hfiguiere** [comment]
that's managed by inkscape upstream. 

Note that these instruction will lead to always be up to date as long as the flatpak is up to date, which is what is expected. I see no problem here.

**Comment by doctormo** [comment]
Yes, I think we have reached an agreement here.

The upstream volunteers (all zero of them) can no longer keep this record up to date, so it will not be added to future releases.

The question for your downstream is that you understand this situation. And I think you do, although it's taken us a while to get here.

**Comment by hfiguiere** [comment]
> Yes, I think we have reached an agreement here.
> 
> The upstream volunteers (all zero of them) can no longer keep this record up to date, so it will not be added to future releases.

I'm not even sure what's your thinking here, but there is **NOTHING to change** on that page to always get the last flatpak version of Inkscape. There no change needed when the flatpak is updated. It just work. You are inventing problems that don't exist.

If you use the instructions on said page, you get Inkscape 1.1 as a flatpak from Flathub. 

Here on my Fedora, GNOME software will update (or tell me to) when there is an updated Inkscape. We, the Flathub maintainers, tend to be quite up to date there too.

So I still don't understand what your issue is. But for sure removing the Flatpak would make a great disservice to your users.

**Comment by doctormo** [comment]
Yes, there is nothing to change. That's what we're going to do, change nothing. No removals, no additions. No changes. Which actually fits well with our other distro based packages which aren't on the website either. I know you're struggling to understand because our system isn't know to you, that's not your fault. It's not a static link.

**Comment by boredsquirrel** [comment]
Fyi Inkscape does no longer list the Flatpak on their page...

**Comment by AsciiWolf** [comment]
It's sad to see that the Inkscape snap is verified, regularly updated and taken good care of although snap is basically a Ubuntu-only thing that is considered very niche among Linux users, and Flatpak on the other hand is treated so badly by the Inkscape upstream even though it has more than 740k users. Please, reconsider this. Thanks!

**Comment by doctormo** [comment]
> It's sad to see that the Inkscape snap is verified, regularly updated and taken good care of although snap is basically a Ubuntu-only thing that is considered very niche among Linux users, and Flatpak on the other hand is treated so badly by the Inkscape upstream even though it has more than 740k users. Please, reconsider this. Thanks!

Get involved. I hate snaps so much I ripped a hole in my dev machine to get rid of them, I use flatpaks by preference on all of my computers.

Inkscape's downstream packaging needs someone who's interested in working with us, who might be more polite than I was able to be in this thread.

**Comment by AsciiWolf** [comment]
I sadly already maintain over 30 Flatpaks on Flathub and my free time is very limited. Anyway, what about the current maintainer (@hfiguiere)?

**Comment by doctormo** [comment]
They've exhibited no interest in being part of the inkscape project as far as I know.

In order to be verified, a packager has to be a member of the project, it's no good having free spirits doing whatever they feel like and never talking to the project that they are supposed to be representing. To be a casual, disconnected packager is to be unverified.

**Comment by hfiguiere** [comment]
There, I invited you to the repo. There was probably a nicer way to ask. Also I removed myself from the maintainers, so it's only you and @matze  + the flathub maintainers which I belong.

No. Longer. My. Responsibility.

**Comment by doctormo** [comment]
I agree, I wasn't very nice. I'll try and communicate better in the future.

**Comment by doctormo** [comment]
It doesn't look like I can invite anyone else to collaborate on this repository, is the invitation limited? I was hoping that if you are quitting, which you made it sound like you probably are, that the full permissions for the flatpak would be given over to a new maintainer, or in this case the project itself.

**Comment by AsciiWolf** [comment]
As far as I know, maintainers do not have full permissions to their Flathub Git repos. For security reasons.

If you want to add new people to cooperate with the repo, you have to ask someone from the [Flathub staff](https://github.com/orgs/flathub/people).

**Comment by doctormo** [comment]
Good to know, thanks.

**Comment by VaibhavMalik4187** [comment]
Dear Flathub Maintainers,

I am writing to let you know that I am interested in becoming a member/maintainer of this repository. I have been following the Inkscape project for some time and am familiar with its development process.

Please let me know the requirements and steps to becoming a member/maintainer for this repository.

Thank you for your time and consideration.

**Comment by Verhoeckx** [comment]
> Dear Flathub Maintainers,
> 
> I am writing to let you know that I am interested in becoming a member/maintainer of this repository. I have been following the Inkscape project for some time and am familiar with its development process.
> 
> Please let me know the requirements and steps to becoming a member/maintainer for this repository.
> 
> Thank you for your time and consideration.


Did you ever get access? Is it possible for you to update the flatpak version of Inkscape to version 1.4.2?
Flatpak is my main way to use Inkscape on my Fedora workstation.
