### ISSUE TITLE
New Screenshot

### ISSUE THREAD

**Issue by Byrdg** [flathub/org.inkscape.Inkscape#96]
Hey, I have this screenshot (attached) that I think could complement the ones available in Flathub. If its OK to update it, can you please point me to the appdata XML source?
![Screenshot from 2021-11-09 15-34-51](https://user-images.githubusercontent.com/94136706/141365441-ad53f1df-ce8c-4460-acaa-f585ac2da3f7.png)
"

**Comment by hfiguiere** [comment]
Flathub just uses the appdata that is coming from upstream. So you should file this with them.
