### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by ziegenberg** [flathub/org.inkscape.Inkscape#97]
### Steps to reproduce:

- install Inkscape as Flatpak
- open Inkscape
- from the top menu open `Extentsions` > `Manage Extensions...`

### What happened?

The following error is shown:

```
/app/share/inkscape/extensions/inkex/command.py:73: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Traceback (most recent call last):
  File "/app/share/inkscape/extensions/extension-manager-bootstrap.py", line 133, in <module>
    Bootstrap().run()
  File "/app/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/app/share/inkscape/extensions/extension-manager-bootstrap.py", line 78, in effect
    if self.install_fallback():
  File "/app/share/inkscape/extensions/extension-manager-bootstrap.py", line 96, in install_fallback
    from urllib3.exceptions import NewConnectionError
ModuleNotFoundError: No module named 'urllib3'
```

### What should have happened?

The extension manager should open.

#### Inkscape Version and Operating System:

```
Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20)

    GLib version:     2.70.1
    GTK version:      3.24.30
    glibmm version:   2.66.2
    gtkmm version:    3.24.5
    libxml2 version:  2.9.12
    libxslt version:  1.1.34
    Cairo version:    1.17.4
    Pango version:    1.49.2
    HarfBuzz version: 2.8.2
    Poppler version:  21.08.0

    OS version:       Fedora Linux 35 (Thirty Five)
```

### Additional information

This does not happen when installed via the regular package manager.

[As requested on the Inkscape extensions GitLab issue tracker](https://gitlab.com/inkscape/extensions/-/issues/431#note_745788750) this is now also reported here. There it was noted that: `python3-virtualenv` may be missing, as `urllib3` is meant to be imported as part of a fallback script.

**Comment by hfiguiere** [comment]
Are you sure you are using the version from flathub?
1. I can't reproduce
2. urllib3 IS installed.

The information about the OS is really not what the flatpak from flathub uses: poppler is already at version 21.09, and other version aren't what's in there.

**Comment by ziegenberg** [comment]
It could be I got redirected to the wrong flatpak registry. I installed it from registry.fedoraproject.org. I opened the bug now with the Fedora Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2029190

And I confirm when installed from flathub it works as expected. So I'm sorry for making some noise here.
